// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC7joDMotc6Clm5LwTYZKa8Sl56Qob6K7w',
    appId: '1:239897256756:android:f8e51b4ca345b1640a7b61',
    messagingSenderId: '239897256756',
    projectId: 'flutter-hackathon-prd',
    storageBucket: 'flutter-hackathon-prd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDIJvsF8N0tNnLisaURnQyKapjlKAXD-5w',
    appId: '1:239897256756:ios:97bd64354d344c770a7b61',
    messagingSenderId: '239897256756',
    projectId: 'flutter-hackathon-prd',
    storageBucket: 'flutter-hackathon-prd.appspot.com',
    iosBundleId: 'com.beengineer.prd',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB1eWqdkUUoknJnpStwmZ3jRwor-7tXwFY',
    appId: '1:239897256756:web:d747f9256636c0290a7b61',
    messagingSenderId: '239897256756',
    projectId: 'flutter-hackathon-prd',
    authDomain: 'flutter-hackathon-prd.firebaseapp.com',
    storageBucket: 'flutter-hackathon-prd.appspot.com',
  );
}
